### ISSUE TITLE
SFTP Remote Upload not working

### ISSUE THREAD

**Issue by stuartmaxwell** [thanethomson/statik#107]
I was unable to get the SFTP remote upload working. This is the error I was getting when running the `statik -u SFTP` command:

```
Exception caught while attempting to generate project
Traceback (most recent call last):
  File "/home/stuart/.local/share/virtualenvs/tiny-i4BzTY3h/lib/python3.6/site-packages/statik/cmdline.py", line 218, in main
    rm_remote=args.clear_remote
  File "/home/stuart/.local/share/virtualenvs/tiny-i4BzTY3h/lib/python3.6/site-packages/statik/upload.py", line 48, in upload_sftp
    ssh_config = StatikConfig(input_path).remote['sftp']
AttributeError: 'StatikConfig' object has no attribute 'remote'
```

After some digging around in the code I fixed it by adding the following line to the `__init__` method in the `StatikConfig` class (I added it to line 72):

```python
        self.remote = self.vars.get("remote")
```

With that single line added, I was able to publish to SFTP successfully.

**Comment by thanethomson** [comment]
SFTP functionality has been changed significantly in v0.23.0 now.
