### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by gjcarneiro** [thanethomson/statik#31]
It doesn't seem to work in Python 3.  What a shame...
```
(env) 02:39:47 (master) /tmp/statik/examples/blog$ statik
Project path configured as: /tmp/statik/examples/blog
Error caught: name 'unicode' is not defined
```

**Comment by thanethomson** [comment]
Which version of Python are you using? At present, Statik only supports Python 3.5+ (see the requirements in the `README.md`).

**Comment by gjcarneiro** [comment]
I simply tried to build the example blog with Python 3.6 (also tried 3.5), and it doesn't work:
```
(env) 06:09:26 (master) /tmp/statik$ pip install statik
Collecting statik
  Using cached statik-0.7.0.tar.gz
[...]
(env) 06:09:56 (master) /tmp/statik/examples/blog$ statik
Project path configured as: /tmp/statik/examples/blog
Error caught: name 'unicode' is not defined
(env) 06:09:57 (master) /tmp/statik/examples/blog$ python
Python 3.6.0b2 (default, Oct 11 2016, 05:27:10) 
[GCC 6.2.0 20161005] on linux
```
Because of the `name 'unicode' is not defined` part I thought it was because the code wasn't prepared to run in Python 3, because in Python 3 there is no `unicode` type, that only exists in Python 2.

As a side note, I don't like the `Error caught: name 'unicode' is not defined` handling at all.  You shouldn't hide Python tracebacks, that is an anti-pattern: now I'm not even able to debug where this error comes from...

**Comment by thanethomson** [comment]
This is very strange. I've enabled verbose exception logging now in `v0.7.1`. I've tested now with Python 3.5.1 and 3.5.2, and the unit tests, `blog` example and the [getstatik.com](https://github.com/thanethomson/getstatik-site) code all build just fine for me (even with a fresh `virtualenv`). I also don't use the `unicode` keyword at all in the codebase (a `grep -ir 'unicode' statik` in the source directory will show this). It could be in one of the dependency libraries.

Please update to `v0.7.1` and send me your traceback? Also, which OS are you running?

**Comment by gjcarneiro** [comment]
Finally solved it.  See why you should not hide tracebacks?  Tracebacks are an essential part of Python, don't hide them please.

```
(env) 11:06:36 (master) /tmp/statik/examples/blog$ statik
Project path configured as: /tmp/statik/examples/blog
Using encoding: None
Error caught: name 'unicode' is not defined
Traceback (most recent call last):
  File "/tmp/statik/env/lib/python3.5/site-packages/statik-0.8.0-py3.5.egg/statik/project.py", line 104, in generate
    in_memory_result = self.process_views()
  File "/tmp/statik/env/lib/python3.5/site-packages/statik-0.8.0-py3.5.egg/statik/project.py", line 239, in process_views
    output = deep_merge_dict(output, view.process(self.db))
  File "/tmp/statik/env/lib/python3.5/site-packages/statik-0.8.0-py3.5.egg/statik/views.py", line 128, in process
    return self.process_complex(db) if self.complex else self.process_simple(db)
  File "/tmp/statik/env/lib/python3.5/site-packages/statik-0.8.0-py3.5.egg/statik/views.py", line 170, in process_simple
    final_value=self.template.render(**self.context),
  File "/tmp/statik/env/lib/python3.5/site-packages/Jinja2-2.8-py3.5.egg/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/tmp/statik/env/lib/python3.5/site-packages/Jinja2-2.8-py3.5.egg/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/tmp/statik/env/lib/python3.5/site-packages/Jinja2-2.8-py3.5.egg/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/tmp/statik/examples/blog/templates/slugify-example.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/tmp/statik/examples/blog/templates/base.html", line 9, in top-level template code
    {% block body %}{% endblock %}
  File "/tmp/statik/examples/blog/templates/slugify-example.html", line 10, in block "body"
    <li>{{ post.title }} -&gt; {{ post.title|slugify }}</li>
  File "/tmp/statik/examples/blog/templatetags/my_filters.py", line 10, in filter_slugify
    return slugify(s)
  File "/tmp/statik/env/lib/python3.5/site-packages/slugify.py", line 24, in slugify
    unicode(
NameError: name 'unicode' is not defined
```

So, it turns out I pip installed a package called `sluglify` that is not Python 3 compatible.  I didn't notice the `requirements.txt` which correctly indicates `python-slugify`.  Now it works.

Sorry for the noise.

**Comment by thanethomson** [comment]
No worries. I realised I didn't actually have a `requirements.txt` in the repo for the blog example, so I just added it today. And apologies for the difficulty in debugging! Hope it's easier from now on :grin:
