### ISSUE TITLE
Error caught super() / no "shutdown"

### ISSUE THREAD

**Issue by vindarel** [thanethomson/statik#32]
Hi !
I tried to re-run what I think is the example project of the wiki walkthrough.
with statik 0.7.0:

```
$ statik                                                                      
Project path configured as: /home/vince/bacasable/statiktest
Error caught: super() takes at least 1 argument (0 given)
Unable to clean up properly: 'NoneType' object has no attribute 'shutdown'
```
Any idea ? (tried with py2 and 3)

ps: idea: provide the example project of the walkthrough as a git project, so that I'm sure I'm doing well, I can extend this base, and so we can test and update it with the newer statik versions.

**Comment by vindarel** [comment]
ps: same error when trying with getstatik-site sources.

**Comment by thanethomson** [comment]
Strange. Could be related to #31. Please update to `v0.7.1` and send your exception traceback? I've enabled verbose exception logging now in `v0.7.1`.

I can build the `getstatik-site` sources just fine with Python 3.5.1 and 3.5.2 at the moment.

**Comment by vindarel** [comment]
Now I can build getstatik-site sources.
My traceback for my project (statik 0.8):

```
$ statik                                                                       *[master] 
Project path configured as: /home/vince/bacasable/statiktest
Using encoding: None
Error caught: while parsing a block mapping
  in "<unicode string>", line 1, column 1:
    path:
    ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 5, column 2:
     template: post
     ^
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/statik/project.py", line 91, in generate
    self.views = self.load_views()
  File "/usr/local/lib/python2.7/dist-packages/statik/project.py", line 200, in load_views
    template_env=self.template_env,
  File "/usr/local/lib/python2.7/dist-packages/statik/views.py", line 25, in __init__
    super(StatikView, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/statik/common.py", line 43, in __init__
    self.vars = yaml.load(self.file_content) if len(self.file_content) else {}
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
ParserError: while parsing a block mapping
  in "<unicode string>", line 1, column 1:
    path:
    ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 5, column 2:
     template: post
     ^
Unable to clean up properly: 'NoneType' object has no attribute 'shutdown'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/statik/project.py", line 123, in generate
    self.db.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'
```
It wasn't super clear, but because of "template: post" I recognized there's a pb in a yaml file. Indeed, I had a badly indented line. Fixed !

**Comment by thanethomson** [comment]
Awesome - glad the traceback helped! :grin:
