### ISSUE TITLE
"statik" encounter error

### ISSUE THREAD

**Issue by luckypoem** [thanethomson/statik#34]
hi.

root@AR:/usr/local/statik-site# statik
Traceback (most recent call last):
  File "/usr/local/bin/statik", line 7, in <module>
    from statik.cmdline import main
  File "/usr/local/lib/python2.7/dist-packages/statik/cmdline.py", line 11, in <module>
    from statik.watcher import watch
  File "/usr/local/lib/python2.7/dist-packages/statik/watcher.py", line 6, in <module>
    import httpwatcher
  File "/usr/local/lib/python2.7/dist-packages/httpwatcher/__init__.py", line 4, in <module>
    from httpwatcher.server import *
  File "/usr/local/lib/python2.7/dist-packages/httpwatcher/server.py", line 18, in <module>
    from httpwatcher.filesystem import FileSystemWatcher
  File "/usr/local/lib/python2.7/dist-packages/httpwatcher/filesystem.py", line 15, in <module>
    from tornado.queues import Queue
ImportError: No module named queues
root@AR:/usr/local/statik-site# pip install queues
Requirement already satisfied: queues in /usr/local/lib/python2.7/dist-packages
root@AR:/usr/local/statik-site#
then i ran "statik", still encountered error above.

hwo to fix it?
thank you.

**Comment by FuzzyWuzzie** [comment]
Perhaps try python3?

**Comment by luckypoem** [comment]
@FuzzyWuzzie 
in virtualenv ,there is no issue,even if it's under python2.

**Comment by thanethomson** [comment]
If it works under virtualenv but not in your system installation (i.e. without virtualenv) then it sounds like you've got a dependency issue or wrong dependency version.

For that specific error, it looks to me as though your Tornado dependency is broken or incorrect.

**Comment by thanethomson** [comment]
Is this still an issue? Closing for now.
