### ISSUE TITLE
statik --watch: OSError: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by tombreit** [thanethomson/statik#42]
On  a Debian 9.1 host, when I try to run the examples/blog project or a custom statik project via `statik --watch`, I got the following error: 

```
(venv) breitner@breitner-vm-debian-x:~/projects/statik/examples/blog$ statik --watch
Project path configured as: /home/breitner/projects/statik/examples/blog
Using encoding: utf-8
Writing output file: /home/breitner/projects/statik/examples/blog/public/rand-example/index.html
Writing output file: /home/breitner/projects/statik/examples/blog/public/2016/06/01/first-post/index.html
Writing output file: /home/breitner/projects/statik/examples/blog/public/2016/06/04/second-post/index.html
Writing output file: /home/breitner/projects/statik/examples/blog/public/2016/06/30/html-content-test/index.html
Writing output file: /home/breitner/projects/statik/examples/blog/public/index.html
Writing output file: /home/breitner/projects/statik/examples/blog/public/slugify-example/index.html
Wrote 6 output file(s) to folder: /home/breitner/projects/statik/examples/blog/public
Copying assets from /home/breitner/projects/statik/examples/blog/assets to /home/breitner/projects/statik/examples/blog/public/assets...
Copied 1 asset(s)
--- Logging error ---
Traceback (most recent call last):
  File "/home/breitner/projects/statik/examples/blog/venv/lib/python3.5/site-packages/statik/cmdline.py", line 102, in main
    safe_mode=args.safe_mode)
  File "/home/breitner/projects/statik/examples/blog/venv/lib/python3.5/site-packages/statik/watcher.py", line 75, in watch
    open_browser=open_browser
  File "/home/breitner/projects/statik/examples/blog/venv/lib/python3.5/site-packages/httpwatcher/cmdline.py", line 49, in watch
    server.listen()
  File "/home/breitner/projects/statik/examples/blog/venv/lib/python3.5/site-packages/httpwatcher/server.py", line 98, in listen
    super(HttpWatcherServer, self).listen(self.port, address=self.host, **kwargs)
  File "/home/breitner/projects/statik/examples/blog/venv/lib/python3.5/site-packages/tornado/web.py", line 1943, in listen
    server.listen(port, address)
  File "/home/breitner/projects/statik/examples/blog/venv/lib/python3.5/site-packages/tornado/tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/breitner/projects/statik/examples/blog/venv/lib/python3.5/site-packages/tornado/netutil.py", line 197, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 981, in emit
    msg = self.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 831, in format
    return fmt.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 568, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.5/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/breitner/projects/statik/examples/blog/venv/bin/statik", line 11, in <module>
    sys.exit(main())
  File "/home/breitner/projects/statik/examples/blog/venv/lib/python3.5/site-packages/statik/cmdline.py", line 113, in main
    logger.exception("Exception caught while attempting to generate project", e)
Message: 'Exception caught while attempting to generate project'
Arguments: (OSError(99, 'Cannot assign requested address'),)
(venv) breitner@breitner-vm-debian-x:~/projects/statik/examples/blog$ 
```

I followed your setup/installation procedure from your documentation, using python 3.5.3 and a virtual environment. Generating the site via `statik` finished without any error (see above).

The same projects run just fine on another Debian Stretch host. Unfortunately, I have no idea how I can fix this error...

**Comment by thanethomson** [comment]
What else have you got running on that Debian 9.1 host? By default Statik binds to `localhost` port 8000. Check if anything else is bound to `localhost` (or `127.0.0.1`) port 8000:

```bash
> lsof -Pni4 | grep LISTEN
```

Looks to me like you've got an IP address/port conflict. Also, try binding Statik to a different host/port:

```bash
> statik --watch --host 0.0.0.0 --port 8001
```

**Comment by tombreit** [comment]
That' weird - nothing is listening on 127.0.0.1 on port 8000. And I could bind Statik to all kind of IP/port combination - but not on `localhost`: 

OK:
```
> statik --watch --host 127.0.0.1 --port 8000
...
/statik/examples/blog/public/assets...
Copied 1 asset(s)
Started HTTP watcher server at http://127.0.0.1:8000/
```

Not OK: 
```
> statik --watch --host localhost --port 8000
...
/statik/examples/blog/public/assets...
Copied 1 asset(s)
--- Logging error ---
Traceback (most recent call last):
  File "/home/breitner/projects/statik/examples/blog/venv/lib/python3.5/site-packages/statik/cmdline.py", line 102, in main
    safe_mode=args.safe_mode)
  File "/home/breitner/projects/statik/examples/blog/venv/lib/python3.5/site-packages/statik/watcher.py", line 75, in watch
    open_browser=open_browser
  File "/home/breitner/projects/statik/examples/blog/venv/lib/python3.5/site-packages/httpwatcher/cmdline.py", line 49, in watch
    server.listen()
  File "/home/breitner/projects/statik/examples/blog/venv/lib/python3.5/site-packages/httpwatcher/server.py", line 98, in listen
    super(HttpWatcherServer, self).listen(self.port, address=self.host, **kwargs)
  File "/home/breitner/projects/statik/examples/blog/venv/lib/python3.5/site-packages/tornado/web.py", line 1943, in listen
    server.listen(port, address)
  File "/home/breitner/projects/statik/examples/blog/venv/lib/python3.5/site-packages/tornado/tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/breitner/projects/statik/examples/blog/venv/lib/python3.5/site-packages/tornado/netutil.py", line 197, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
...
```

So it seems my `localhost` name resolution is confused and that has nothing to do with Statik.  Thanks a lot for your hints.

**Comment by thanethomson** [comment]
Cool, closing for now then 😀 👍

**Comment by tombreit** [comment]
Strange, django runserver runs happily on `localhost` on port `8000`: 


```
(_venv) $ python manage.py runserver localhost:8000
Performing system checks...

System check identified no issues (0 silenced).
August 07, 2017 - 13:41:04
Django version 1.10.7, using settings 'project.settings'
Starting development server at http://localhost:8000/
Quit the server with CONTROL-C.
```
Perhaps it's not an issue with my name resolution but in `httpwatcher`?
